= Prequisites Elisisan

|===
| Nama | Deskripsi 
|Programming Language | PHP CLI >= 7.1.x 
|Composer Package Manager | https://getcomposer.org/download/[]
| Database | MySQL (>= 5.5.x)
| | PostgreSQL (>= 9.5.5) |
|===
== Tools

Beberapa tools yang disarankan untuk Development adalah sebagai berikut:

. MAMP
. Visual Code Studio
. Sublime Text

== Local Machine Setup

. Download _project_ ini dari github _repository_ "https://github.com/sepulsa/elisian".
. Buat database dengan nama `elisian` di dalam _local environment_-mu.
. `cp .env.example .env` dan atur _local configurations_.
. `composer install` untuk _install dependency packages_.
. `php artisan migrate --seed` untuk _migrate_ dan _seeding_ si _database_.
. `sudo chmod -R 0777 storage && sudo chmod -R 0777 public/file` untuk memastikan _storage directories_ punya _permissions_ yang tepat.
. Atur _supervisor configuration_-mu seperti berikut:
+
....
 [program:elisian-worker]

 process_name=%(program_name)s_%(process_num)02d

 command=php /home/forge/example.com/artisan queue:work --sleep=3 --tries=3 --daemon

 autostart=true

 autorestart=true

 user=forge

 numprocs=3

 redirect_stderr=true

 stdout_logfile=/home/forge/example.com/storage/logs/supervisor.l
....

. `composer dump-autoload && php artisan clear-compiled && php artisan auth:clear-resets && php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan view:clear` untuk membersihkan _project cache_.
