= Elisian dari KB

== Summary

=== Informasi Umum

Elisian adalah pengganti Aplhaboard, yang merupakan _dashboard_ yang digunakan untuk menampilkan semua data yang dibutuhkan oleh _partner_ dan _biller/operators_(telco).

Elisian dikembangkan untuk kebutuhan _partner_ berupa sebuah _dashboard_ untuk menampilkan informasi yang dibutuhkan oleh _partner_ sehingga dapat diakses dengan mudah sesuai dengan kebutuhan.

Untuk transaksi yang bersifat _real time_, Elisian membaca data dari _direct slave_ Kraken sementara untuk transaksi tidak bersifat _real time_, Elisian membaca data dari Postgree (Sepulsa _Reporting_).

=== Anggota Tim Elisian

|===
| Role | Team | Name
| Product Owner | Sentinel | Jeremy Minardi
 | Development Manager | Sentinel | Roy Gunawan |  Lead Developer | Sentinel | Reza Fahlevi  
 |Lead Quality Engineer | Otter | Marco Ichwan Bosch 
 | Lead System Analyst | Pelican | Gabriel Stevano |
|===

== Informasi Teknis


<<elisian/url-elisian.adoc#, System URL Elisian>>


<<elisian/architecture-elisian.adoc#, Architecture Elisian>>

<<elisian/technology-elisian.adoc#, Technology Elisian>>

<<elisian/environment-elisian.adoc#, Environment Elisian>>

<<elisian/database-elisian.adoc#, Database Elisian>>


<<elisian/release-deployment-elisian.adoc#, Release and Deployment Elisian>>


== Onboarding Information


<<elisian/dev-onboarding-elisian.adoc#, Developer Onboarding Elisian>>


<<elisian/development-elisian.adoc#, Development Elisian>>


<<elisian/naming-convention-elisian.adoc#, Naming Convention Elisian>>


== Dokumentasi


https://github.com/sepulsa/elisian/releases[*Release Notes*]
