= Sentinel from KB

== Overview

Sentinel adalah _dashboard_ khusus untuk Tim OPS (Operations) dalam menjalankan tugas kesehariannya.
Diharapkan pada tahun 2019 Sentinel sudah dapat menggunakan _realtime data_ yang berasal dari data Stream.

Nama lain dari _dashboard_ ini adalah _kraken admin phase 2_.
Melalui Sentinel kita dapat melihat data transaksi, melakukan pengecekan status produk yang tersedia, menambahkan produk, _partner_, dan _operator_.

=== Informasi Umum*

==== Sistem

Sentinel Web Application (FE)

Aplikasi Web Sentinel adalah UI Interface berupa Web Dashboard yang terhubung dengan beberapa sistem,di antaranya adalah: Kraken, Pollux, Sentinel Backend.

Sentinel System (BE)

Sistem Sentinel berfungsi untuk otentikasi pengguna dan fungsi-fungsi lainnya yang belum/tidak dapat disediakan oleh sistem lainnya (Kraken, Pollux, dan lainnya).

=== Anggota Tim Sentinel

|===
| Role | Team | Name 
| Product Owner | Jeremy Minardi | 
| Development Manager | Roy Gunawan |
 | Lead Software Engineer | Somy Andriyanto | 
 | Lead Quality Engineer | Marco Ichwan Bosch | | Lead System Analyst | Gabriel Stevano |

|===

== Informasi Teknis


<<sentinel/url-sentinel.adoc#, System URL Sentinel>>

<<sentinel/architecture-sentinel.adoc#, Architecture Sentinel>>

<<sentinel/technology-sentinel.adoc#, Technology Sentinel>>

<<sentinel/environment-sentinel.adoc#, Environment Sentinel>>

<<sentinel/release-deploy-sentinel.adoc#, Release and Deployment Sentinel>>

<<sentinel/smartbiller-sentinel.adoc#, Smart Biller Sentinel>>


== Onboarding Information

<<sentinel/dev-onboarding-sentinel.adoc#, Developer Onboarding Sentinel>>

<<sentinel/development-sentinel.adoc#, Development Sentinel>>

<<sentinel/naming-convention-sentinel.adoc#, Naming Convention Sentinel>>

== Dokumentasi

https://github.com/sepulsa/kraken-admin/releases[Release Notes]

<<sentinel/adr-doc-sentinel.adoc#, ADR Document Sentinel>>
